###
GET http://localhost:3000/songs

###
GET http://localhost:3000/songs/3

###
POST http://localhost:3000/songs
content-type: application/json

{
  "title": "The Joker",
  "album": "The Joker",
  "artist": "Steve Miller Band",
  "year": 1973
}

###
PATCH http://localhost:3000/songs/7
content-type: application/json

{
  "title": "The Joker",
  "album": "The Joker",
  "artist": "Steve Miller Band",
  "year": 1973
}

###
DELETE http://localhost:3000/songs/9
